### PR TITLE
Fix Invalidation of Dynamic Dependencies

### LINKED ISSUE #1510: After popping frame from execution context visualization shows outdated value.
### General Summary

When I modify a function, then after 

### Steps to Reproduce

In IDE:
1. Create node `4`
2. Select it and collapse with ctrl/cmd + g
3. Enter the node created by collapsing
4. Change the value from `4` to `5`
5. go out to the main function
6. Show visualization on node created by collapsing

### Expected Result
`5` in the visualization

### Actual Result
`4`

### Enso Version

0.2.4

### PR DESCRIPTION
**Pull request by 4e6**
### Pull Request Description

close #1510 

IDE attaches external id to the method definition, and ChangesetBuilder was using this id to search for dynamic dependencies. It occurred that dependency analysis doesn't work this way. The fix is to revert the change from #1495 and do not index dynamic symbols with their external ids, and then query dependencies using only the symbol.

Changelog:
- revert: change from #1495, where dynamic dependencies come with external ids.

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the [Scala](https://github.com/enso-org/enso/blob/main/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/main/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/main/docs/style-guide/rust.md) style guides.
- [x] All documentation and configuration conforms to the [markdown](https://github.com/enso-org/enso/blob/main/docs/style-guide/markdown.md) and [YAML](https://github.com/enso-org/enso/blob/main/docs/style-guide/yaml.md) style guides.
- [x] All code has been tested where possible.

### CODE REVIEW

File: engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala [hunk 1]
```diff
@@ -1163,6 +1163,10 @@ class RuntimeServerTest
     val moduleName = "Test.Main"
     val metadata   = new Metadata
 
+    @scala.annotation.unused
+    val fooDefinition = metadata.addItem(26, 22)
+    @scala.annotation.unused
+    val fooName = metadata.addItem(26, 3)
```
Comment (iamrecursion) [inline engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala]: Why assign these if they're not used? Just call `metadata.addItem`.

**Review by iamrecursion — APPROVED** [review]
Looks fine to me, but please get Adam to check that these artefacts work properly in the IDE and truly fix the issue before merging.

File: engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala (hunk 1 above)
Comment (4e6) [reply engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala]: The name is just a note to keep track of what is annotated. I can use a comment instead :+1:
