### PR TITLE
Fix Documentation Comments

### LINKED ISSUE #1193: Language Server Sometimes Loses Documentation
### General Summary

The documentation added in the libraries is displayed in the IDE (panel next to searcher). For most of the functions/methods the documentation is not available. @farmaazon confirmed that IDE is not getting the docs from the Language Server.
### Steps to Reproduce

Open IDE with project manager 
open searcher with `Shift` + `Tab` 
try to find map 
### Expected Result

`map` with documentation available
### Actual Result

Zrzut ekranu 2020-10-6 o 11 54 08

### Enso Version

Enso Project Manager
Version:    0.1.0
Built with: scala-2.13.3 for GraalVM 20.2.0
Built from: main* @ 3d65ffd3cd4cdeb93f3c27dc40874d31390ffdc9
Running on: OpenJDK 64-Bit Server VM, GraalVM Community, JDK 11.0.8+10-jvmci-20.2-b03
            Mac OS X 10.15.6 (x86_64)

### PR DESCRIPTION
**Pull request by 4e6**
### Pull Request Description

close #1193 

`DocumentationComments` pass attaches docstrings to the next encountered expression. When the next expression is a type signature, the doc is attached to it.

Changelog:
- ~~fix: `DocumentationComments` pass skips the type ascriptions when processing the docs.~~
- fix: Update `TypeFunctions` and `TypeSignature` passes to preserve the documentation comments.
- add: `SuggestionBuilder` support functions in type signatures. 

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the [Scala](https://github.com/enso-org/enso/blob/main/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/main/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/main/docs/style-guide/rust.md) style guides.
- [x] All documentation and configuration conforms to the [markdown](https://github.com/enso-org/enso/blob/main/docs/style-guide/markdown.md) and [YAML](https://github.com/enso-org/enso/blob/main/docs/style-guide/yaml.md) style guides.
- [x] All code has been tested where possible.

### CODE REVIEW

File: engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/DocumentationComments.scala [hunk 1]
```diff
@@ -84,6 +84,8 @@ case object DocumentationComments extends IRPass {
       case doc: IR.Comment.Documentation =>
         lastDoc = Some(doc)
         None
+      case typeAscription: IR.Type.Ascription =>
+        Some(typeAscription.asInstanceOf[T])
```
Comment (iamrecursion) [inline engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/DocumentationComments.scala]: This isn't how this should be handled. Instead of ignoring type ascriptions for the purposes of attaching docs, the documentation should be _assigned_ to the type ascription, and then during the `TypeSignatures` pass the associated documentation should be moved onto the definition itself.

**Review by iamrecursion — CHANGES_REQUESTED** [review]

File: engine/runtime/src/test/scala/org/enso/compiler/test/context/SuggestionBuilderTest.scala [hunk 2]
```diff
@@ -416,6 +476,62 @@ class SuggestionBuilderTest extends CompilerTest {
...
+          arguments = Seq(
+            Suggestion.Argument("this", "Nil", false, false, None)
+          ),
+          selfType      = "Nil",
+          returnType    = "List",
+          documentation = Some(" a method")
+        )
+      )
+    }
+
```
Comment (iamrecursion) [inline engine/runtime/src/test/scala/org/enso/compiler/test/context/SuggestionBuilderTest.scala:534]: Please also add some types for local variables with type signatures. The suggestions should also work properly there too.

**Review by iamrecursion — CHANGES_REQUESTED** [review]

**Review by iamrecursion — APPROVED** [review]
