### PR TITLE
Send Method Call Updates After Popping the Frame

### LINKED ISSUE #1029: Missing `executionContext/expressionValuesComputed` After Popping Frame
### General Summary
Consider the following code:
```
Main.mulAdd = 5

main =
    result = Main.mulAdd
    6
```

Now I run it in IDE. Select the node with `Main.mulAdd` expression. Enter it. Leave it. Try to enter it again — fail. It is impossible to enter it again, because IDE invalidates its computed values registry after pushing or popping the stackframe. However, engine does not send `executionContext/expressionValuesComputed` for the said node after popping the frame from the execution context.

Observe the following communication log:
```
{"jsonrpc":"2.0","id":0,"method":"session/initProtocolConnection","params":{"clientId":"e8b12613-752a-44bf-84ef-8c8ec1e3b02c"}}	127	
{"jsonrpc":"2.0","id":0,"result":{"contentRoots":["d1c75f23-bda3-4738-81fc-d9222d193be3"]}}	91	
{"jsonrpc":"2.0","id":1,"method":"search/getSuggestionsDatabase","params":{}}	77	
{"jsonrpc":"2.0","id":1,"result":{"entries":[{"id":47,"suggestion":{"type":"local","externalId":"2d6c6cae-414b-4174-8450-afabd042ae93","module":"Unnamed.Main","name":"result","returnType":"Any","scope":{"start":{"line":2,"character":6},"end":{"line":4,"character":5}}}},{"id":46,"suggestion":{"type":"method","externalId":"abd6952c-ab14-4574-8b8d-a089142c37cf","module":"Unnamed.Main","name":"main","arguments":[{"name":"this","reprType":"Any","isSuspended":false,"hasDefault":false,"defaultValue":null}],"selfType":"here","returnType":"Number"}},{"id":45,"suggestion":{"type":"method","externalId":"2c980296-5cb9-42ac-adea-095409fa7c3a","module":"Unnamed.Main","name":"mulAdd","arguments":[{"name":"this","reprType":"Any","isSuspended":false,"hasDefault":false,"defaultValue":null}],"selfType":"Main","returnType":"Number"}}],"currentVersion":155}}	849	
{"jsonrpc":"2.0","id":2,"method":"capability/acquire","params":{"method":"search/receivesSuggestionsDatabaseUpdates","registerOptions":{}}}	139	
{"jsonrpc":"2.0","id":2,"result":null}	38	
{"jsonrpc":"2.0","id":3,"method":"text/openFile","params":{"path":{"rootId":"d1c75f23-bda3-4738-81fc-d9222d193be3","segments":["src","Main.enso"]}}}	148	
{"jsonrpc":"2.0","id":3,"result":{"writeCapability":{"method":"text/canEdit","registerOptions":{"path":{"rootId":"d1c75f23-bda3-4738-81fc-d9222d193be3","segments":["src","Main.enso"]}}},"content":"Main.mulAdd = 5\n\nmain =\n result = Main.mulAdd\n 6\n\n\n#### METADATA ####\n[[{\"index\":{\"value\":0},\"size\":{\"value\":4}},\"8f6eec81-a516-4dde-be43-07de625a6653\"],[{\"index\":{\"value\":4},\"size\":{\"value\":1}},\"b95addc1-dffd-4622-ba63-4468d083908c\"],[{\"index\":{\"value\":5},\"size\":{\"value\":6}},\"429638bf-fa87-4071-8114-ca700b46fe81\"],[{\"index\":{\"value\":0},\"size\":{\"value\":11}},\"1e0db7d9-0de1-450d-b137-4fa0e2049a35\"],[{\"index\":{\"value\":12},\"size\":{\"value\":1}},\"68d4054d-00d3-49fa-83bd-0807947e28f0\"],[{\"index\":{\"value\":14},\"size\":{\"value\":1}},\"2c980296-5cb9-42ac-adea-095409fa7c3a\"],[{\"index\":{\"value\":0},\"size\":{\"value\":15}},\"f8e67f93-4366-42f9-aa3e-d1d210002b38\"],[{\"index\":{\"value\":17},\"size\":{\"value\":4}},\"b3dbe0d8-4323-4ca2-aacc-14e3b0473740\"],[{\"index\":{\"value\":22},\"size\":{\"value\":1}},\"186f956b-f402-4648-98ce-8b11bea71a53\"],[{\"index\":{\"value\":28},\"size\":{\"value\":6}},\"743ce364-07f6-465f-8640-11fc0cbf306e\"],[{\"index\":{\"value\":35},\"size\":{\"value\":1}},\"612de1cf-9e9e-464b-be5e-7d6ffaa7c694\"],[{\"index\":{\"value\":37},\"size\":{\"value\":4}},\"fecdad1c-9451-4d2b-a7fd-4aad5550de40\"],[{\"index\":{\"value\":41},\"size\":{\"value\":1}},\"27938428-f93b-429e-9094-2fad6d363c83\"],[{\"index\":{\"value\":42},\"size\":{\"value\":6}},\"edf2376f-4edf-4c43-9111-461dc29cef3d\"],[{\"index\":{\"value\":37},\"size\":{\"value\":11}},\"2d6c6cae-414b-4174-8450-afabd042ae93\"],[{\"index\":{\"value\":28},\"size\":{\"value\":20}},\"7ba77f90-2cf9-4402-a3ab-d6f1e6585d51\"],[{\"index\":{\"value\":53},\"size\":{\"value\":1}},\"20f2ff1b-8932-48e5-ba25-b59d15bf7d58\"],[{\"index\":{\"value\":23},\"size\":{\"value\":31}},\"abd6952c-ab14-4574-8b8d-a089142c37cf\"],[{\"index\":{\"value\":17},\"size\":{\"value\":37}},\"0df7d0e1-a95a-47f3-9ea5-b9e54919db2b\"]]\n{\"ide\":{\"node\":{\"20f2ff1b-8932-48e5-ba25-b59d15bf7d58\":{\"position\":{\"vector\":[-495.9664,199.92416]}},\"2d6c6cae-414b-4174-8450-afabd042ae93\":{\"position\":{\"vector\":[-652.0,87.0]}},\"7ba77f90-2cf9-4402-a3ab-d6f1e6585d51\":{\"position\":{\"vector\":[-584.0,115.0]}},\"32dd808a-0633-4648-994c-691653c6e758\":{\"position\":{\"vector\":[-506.0,116.0]}}}}}","currentVersion":"a03427902ca6c19db8721062925a1839133762ddc1498cca25be7b10"}}	2495	
{"jsonrpc":"2.0","id":4,"method":"executionContext/create","params":{}}	71	
{"jsonrpc":"2.0","id":5,"method":"text/applyEdit","params":{"edit":{"edits":[{"range":{"end":{"character":336,"line":9},"start":{"character":0,"line":0}},"text":"Main.mulAdd = 5\n\nmain =\n result = Main.mulAdd\n 6\n\n\n#### METADATA ####\n[[{\"index\":{\"value\":0},\"size\":{\"value\":4}},\"8f6eec81-a516-4dde-be43-07de625a6653\"],[{\"index\":{\"value\":4},\"size\":{\"value\":1}},\"b95addc1-dffd-4622-ba63-4468d083908c\"],[{\"index\":{\"value\":5},\"size\":{\"value\":6}},\"429638bf-fa87-4071-8114-ca700b46fe81\"],[{\"index\":{\"value\":0},\"size\":{\"value\":11}},\"1e0db7d9-0de1-450d-b137-4fa0e2049a35\"],[{\"index\":{\"value\":12},\"size\":{\"value\":1}},\"68d4054d-00d3-49fa-83bd-0807947e28f0\"],[{\"index\":{\"value\":14},\"size\":{\"value\":1}},\"2c980296-5cb9-42ac-adea-095409fa7c3a\"],[{\"index\":{\"value\":0},\"size\":{\"value\":15}},\"f8e67f93-4366-42f9-aa3e-d1d210002b38\"],[{\"index\":{\"value\":17},\"size\":{\"value\":4}},\"b3dbe0d8-4323-4ca2-aacc-14e3b0473740\"],[{\"index\":{\"value\":22},\"size\":{\"value\":1}},\"186f956b-f402-4648-98ce-8b11bea71a53\"],[{\"index\":{\"value\":28},\"size\":{\"value\":6}},\"743ce364-07f6-465f-8640-11fc0cbf306e\"],[{\"index\":{\"value\":35},\"size\":{\"value\":1}},\"612de1cf-9e9e-464b-be5e-7d6ffaa7c694\"],[{\"index\":{\"value\":37},\"size\":{\"value\":4}},\"fecdad1c-9451-4d2b-a7fd-4aad5550de40\"],[{\"index\":{\"value\":41},\"size\":{\"value\":1}},\"27938428-f93b-429e-9094-2fad6d363c83\"],[{\"index\":{\"value\":42},\"size\":{\"value\":6}},\"edf2376f-4edf-4c43-9111-461dc29cef3d\"],[{\"index\":{\"value\":37},\"size\":{\"value\":11}},\"2d6c6cae-414b-4174-8450-afabd042ae93\"],[{\"index\":{\"value\":28},\"size\":{\"value\":20}},\"7ba77f90-2cf9-4402-a3ab-d6f1e6585d51\"],[{\"index\":{\"value\":53},\"size\":{\"value\":1}},\"20f2ff1b-8932-48e5-ba25-b59d15bf7d58\"],[{\"index\":{\"value\":23},\"size\":{\"value\":31}},\"abd6952c-ab14-4574-8b8d-a089142c37cf\"],[{\"index\":{\"value\":17},\"size\":{\"value\":37}},\"0df7d0e1-a95a-47f3-9ea5-b9e54919db2b\"]]\n{\"ide\":{\"node\":{\"20f2ff1b-8932-48e5-ba25-b59d15bf7d58\":{\"position\":{\"vector\":[-495.9664,199.92416]}},\"2d6c6cae-414b-4174-8450-afabd042ae93\":{\"position\":{\"vector\":[-652.0,87.0]}},\"7ba77f90-2cf9-4402-a3ab-d6f1e6585d51\":{\"position\":{\"vector\":[-584.0,115.0]}},\"32dd808a-0633-4648-994c-691653c6e758\":{\"position\":{\"vector\":[-506.0,116.0]}}}}}"}],"newVersion":"a03427902ca6c19db8721062925a1839133762ddc1498cca25be7b10","oldVersion":"a03427902ca6c19db8721062925a1839133762ddc1498cca25be7b10","path":{"rootId":"d1c75f23-bda3-4738-81fc-d9222d193be3","segments":["src","Main.enso"]}}}}	2619	
{"jsonrpc":"2.0","id":4,"result":{"contextId":"9a09213d-4414-4828-b41e-a32358a6e08b","canModify":{"method":"executionContext/canModify","registerOptions":{"contextId":"9a09213d-4414-4828-b41e-a32358a6e08b"}},"receivesUpdates":{"method":"executionContext/receivesUpdates","registerOptions":{"contextId":"9a09213d-4414-4828-b41e-a32358a6e08b"}}}}	344	
{"jsonrpc":"2.0","id":6,"method":"executionContext/push","params":{"contextId":"9a09213d-4414-4828-b41e-a32358a6e08b","stackItem":{"methodPointer":{"definedOnType":"Main","file":{"rootId":"d1c75f23-bda3-4738-81fc-d9222d193be3","segments":["src","Main.enso"]},"name":"main"},"positionalArgumentsExpressions":[],"thisArgumentExpression":null,"type":"ExplicitCall"}}}	364	
{"jsonrpc":"2.0","id":5,"result":null}	38	
{"jsonrpc":"2.0","id":6,"result":null}	38	
{"jsonrpc":"2.0","id":7,"method":"file/exists","params":{"path":{"rootId":"d1c75f23-bda3-4738-81fc-d9222d193be3","segments":["visualization"]}}}	144	
{"jsonrpc":"2.0","method":"executionContext/expressionValuesComputed","params":{"contextId":"9a09213d-4414-4828-b41e-a32358a6e08b","updates":[{"id":"edf2376f-4edf-4c43-9111-461dc29cef3d","type":null,"shortValue":"UnresolvedSymbol<mulAdd>","methodCall":null}]}}	260	
{"jsonrpc":"2.0","method":"executionContext/expressionValuesComputed","params":{"contextId":"9a09213d-4414-4828-b41e-a32358a6e08b","updates":[{"id":"fecdad1c-9451-4d2b-a7fd-4aad5550de40","type":"Main","shortValue":"Main","methodCall":null}]}}	242	
{"jsonrpc":"2.0","method":"executionContext/expressionValuesComputed","params":{"contextId":"9a09213d-4414-4828-b41e-a32358a6e08b","updates":[{"id":"2d6c6cae-414b-4174-8450-afabd042ae93","type":"Number","shortValue":"5","methodCall":{"file":{"rootId":"d1c75f23-bda3-4738-81fc-d9222d193be3","segments":["src","Main.enso"]},"definedOnType":"Main","name":"mulAdd"}}]}}	365	
{"jsonrpc":"2.0","method":"executionContext/expressionValuesComputed","params":{"contextId":"9a09213d-4414-4828-b41e-a32358a6e08b","updates":[{"id":"7ba77f90-2cf9-4402-a3ab-d6f1e6585d51","type":"Unit","shortValue":"Unit","methodCall":null}]}}	242	
{"jsonrpc":"2.0","method":"executionContext/expressionValuesComputed","params":{"contextId":"9a09213d-4414-4828-b41e-a32358a6e08b","updates":[{"id":"20f2ff1b-8932-48e5-ba25-b59d15bf7d58","type":"Number","shortValue":"6","methodCall":null}]}}	241	
{"jsonrpc":"2.0","method":"executionContext/expressionValuesComputed","params":{"contextId":"9a09213d-4414-4828-b41e-a32358a6e08b","updates":[{"id":"abd6952c-ab14-4574-8b8d-a089142c37cf","type":"Number","shortValue":"6","methodCall":null}]}}	241	
{"jsonrpc":"2.0","method":"executionContext/expressionValuesComputed","params":{"contextId":"9a09213d-4414-4828-b41e-a32358a6e08b","updates":[{"id":"7ba77f90-2cf9-4402-a3ab-d6f1e6585d51","type":"Unit","shortValue":"Unit","methodCall":null}]}}	242	
{"jsonrpc":"2.0","method":"executionContext/expressionValuesComputed","params":{"contextId":"9a09213d-4414-4828-b41e-a32358a6e08b","updates":[{"id":"20f2ff1b-8932-48e5-ba25-b59d15bf7d58","type":"Number","shortValue":"6","methodCall":null}]}}	241	
{"jsonrpc":"2.0","method":"executionContext/expressionValuesComputed","params":{"contextId":"9a09213d-4414-4828-b41e-a32358a6e08b","updates":[{"id":"abd6952c-ab14-4574-8b8d-a089142c37cf","type":"Number","shortValue":"6","methodCall":null}]}}	241	
{"jsonrpc":"2.0","id":7,"result":{"exists":false}}	50	
{"jsonrpc":"2.0","id":8,"method":"executionContext/push","params":{"contextId":"9a09213d-4414-4828-b41e-a32358a6e08b","stackItem":{"expressionId":"2d6c6cae-414b-4174-8450-afabd042ae93","type":"LocalCall"}}}	206	
{"jsonrpc":"2.0","id":8,"result":null}	38	
{"jsonrpc":"2.0","method":"executionContext/expressionValuesComputed","params":{"contextId":"9a09213d-4414-4828-b41e-a32358a6e08b","updates":[{"id":"2c980296-5cb9-42ac-adea-095409fa7c3a","type":"Number","shortValue":"5","methodCall":null}]}}	241	
{"jsonrpc":"2.0","id":9,"method":"executionContext/pop","params":{"contextId":"9a09213d-4414-4828-b41e-a32358a6e08b"}}	118	
{"jsonrpc":"2.0","id":9,"result":null}	38	
{"jsonrpc":"2.0","method":"executionContext/expressionValuesComputed","params":{"contextId":"9a09213d-4414-4828-b41e-a32358a6e08b","updates":[{"id":"7ba77f90-2cf9-4402-a3ab-d6f1e6585d51","type":"Unit","shortValue":"Unit","methodCall":null}]}}	242	
{"jsonrpc":"2.0","method":"executionContext/expressionValuesComputed","params":{"contextId":"9a09213d-4414-4828-b41e-a32358a6e08b","updates":[{"id":"20f2ff1b-8932-48e5-ba25-b59d15bf7d58","type":"Number","shortValue":"6","methodCall":null}]}}	241	
{"jsonrpc":"2.0","method":"executionContext/expressionValuesComputed","params":{"contextId":"9a09213d-4414-4828-b41e-a32358a6e08b","updates":[{"id":"abd6952c-ab14-4574-8b8d-a089142c37cf","type":"Number","shortValue":"6","methodCall":null}]}}	241	
```

Initially, when the execution context is in the main function it gets information about 6 expressions being computed (and actually 3 of them are sent twice — we don't really mind but it is unexpected as well).
Then after entering and leaving node, engine sends `expressionValuesComputed` only for 3 expressions (the ones that were previously reported twice), but other 3 remain uncomputed.

Now, IDE expects to get all the updates every time after entering or leaving node.
Though this could be conceivably a feature, that registry is not invalidated, and the values previously computed are stored by the IDE. But then — the remaining 3 expressions shouldn't be updated. Current behavior doesn't make sense either way.

I expect that:
1. Either all the expressions are reported after changing the stackframe, or we discuss and agree to cache and reuse previously computed values;
2. It should be documented what updates we should expect from the engine after pushing/popping the frame.

### PR DESCRIPTION
**Pull request by 4e6**
### Pull Request Description

close #1029 

The difficulty with sending all the method pointer updates is that some values can be cached, and we don't want to re-execute them. And some values can be invalidated, executed, and send to the user as a value update, and we don't want to re-send them.

PR introduces the `MetodCallsCache` created per frame execution, meaning that it is not persisted in between the runs. The cache tracks which calls have been fired during the program execution (and sent as a notification to the user). When the program finishes, we compute the set of calls that have not been executed and send them to the user as well.

- add: `MethodCallsCache` temporary storage tracking the executed method calls
- add: `sendMethodCallUpdates` flag enabling sending all the method calls of the frame as a value updates

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the [Scala](https://github.com/enso-org/enso/blob/main/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/main/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/main/docs/style-guide/rust.md) style guides.
- [x] All documentation and configuration conforms to the [markdown](https://github.com/enso-org/enso/blob/main/docs/style-guide/markdown.md) and [YAML](https://github.com/enso-org/enso/blob/main/docs/style-guide/yaml.md) style guides.
- [x] All code has been tested where possible.

### CODE REVIEW

File: engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala [hunk 1]
```diff
@@ -79,13 +85,28 @@ trait ProgramExecutionSupport {
...
     callStack match {
-      case Nil => ()
+      case Nil =>
+        methodCallsCache
+          .getNotExecuted(executionFrame.cache.getCalls)
+          .forEach { expressionId =>
+            cachedMethodCallsCallback.accept(
+              new ExpressionValue(
+                expressionId,
+                null,
```
Comment (kustosz) [inline engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala:95]: Use named arguments for the nulls

**Review by kustosz — APPROVED** [review]

File: engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala (hunk 1 above)
Comment (4e6) [reply engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala:95]: Unfortunately, it's a Java class, and it does not support named arguments.
