### PR TITLE
Do not Cache Panics

### LINKED ISSUE #1549: Panic "Name ... could not be found" does not disappear after adding proper import
### General Summary

IDE when inserting node, first add code, and then import. The Language Server behaves, like the import wasn't added.

### Steps to Reproduce

In fresh project in IDE add node `Table.new` picking it from searcher.

### Expected Result

A new node without error

### Actual Result

Error disappears after connecting input. 

### Enso Version

0.2.6

### PR DESCRIPTION
**Pull request by 4e6**
### Pull Request Description

close #1549 

Changelog:
- feat: do not cache panics.

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the [Scala](https://github.com/enso-org/enso/blob/main/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/main/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/main/docs/style-guide/rust.md) style guides.
- [x] All documentation and configuration conforms to the [markdown](https://github.com/enso-org/enso/blob/main/docs/style-guide/markdown.md) and [YAML](https://github.com/enso-org/enso/blob/main/docs/style-guide/yaml.md) style guides.
- [x] All code has been tested where possible.

### CODE REVIEW

File: engine/runtime/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java [hunk 1]
```diff
@@ -378,17 +378,22 @@ public void onReturnValue(EventContext context, VirtualFrame frame, Object resul
...
         callsCache.setExecuted(nodeId);
       } else if (node instanceof ExpressionNode) {
+        boolean isPanic = result instanceof PanicSentinel;
         UUID nodeId = ((ExpressionNode) node).getId();
         String resultType = Types.getName(result);
-        cache.offer(nodeId, result);
+
+        if (!isPanic) {
+          cache.offer(nodeId, result);
+        }
```
Comment (iamrecursion) [inline engine/runtime/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java:390]: Can you put a source note here that explains why this is necessary and the bug that it prevents?

**Review by iamrecursion — APPROVED** [review]
