### PR TITLE
Fix Runtime Jobs Scheduling

### LINKED ISSUE #1304: Project Manager has big delays in sending updates after running for couple hours
### Summary

Right now if Project Manager is running in the background with time it has bigger and bigger delays. I.e. after opening new project it takes up to 5 min to start coloring connections. After working longer with project like:
```
import Base.Data.Json
import Base.Data.Map
import Base.Data.Vector
from Base import all

main = 
    operator1 = File.read "vehicles.json"
    operator2 = Json.parse operator1
    operator3 = operator2.fields
    operator4 = operator3.get "vehicles"
    operator5 = operator4.items
    operator6 = operator5.filter (x -> x.fields.get "longitude" . is_nothing)
```
[vehicles.json.zip](https://github.com/enso-org/enso/files/5571876/vehicles.json.zip)

(building it from scratch, playing around, going away and going back) after adding node `12` I was waiting for around 30 s for types information and another 10 for visualization. Project Manager was running in the background for about 2-3 h

### LINKED ISSUE #1309: SEVERE "An error occurred during execution of EditFileCmd command"
### General Summary

I get the error as in the title after some work in IDE. Usually I hit this issue when try to create from scratch a program described below. [The program will require a vehicles.json file attached here.](https://app.zenhub.com/files/76672223/bfce05cf-e07a-4ddb-9dcd-dae8b7434768/download)

### Steps to Reproduce

I assume there is no project `Unnamed` in the `~/enso/projects` directory.

* Run Project Manager
* Run IDE
* Start adding nodes to make the following graph (change the path in `File.read` accordingly):

### Expected Result

Everything goes smoothly. On each step I can show visualization and see the results.

### Actual Result

At some point the following log appears in console where PM is run:
```
SEVERE: An error occurred during execution of EditFileCmd command
org.enso.interpreter.service.error.FailedToApplyEditsException: Filed to apply edits for file /home/adam-praca/enso/projects/Unnamed/src/Main.enso.
	at org.enso.interpreter.service.ExecutionService.lambda$modifyModuleSources$3(ExecutionService.java:263)
	at java.base/java.util.Optional.ifPresentOrElse(Optional.java:203)
	at org.enso.interpreter.service.ExecutionService.modifyModuleSources(ExecutionService.java:260)
	at org.enso.interpreter.instrument.job.EnsureCompiledJob.applyEdits(EnsureCompiledJob.scala:326)
	at org.enso.interpreter.instrument.job.EnsureCompiledJob.$anonfun$ensureIndexedModules$1(EnsureCompiledJob.scala:65)
	at org.enso.interpreter.instrument.job.EnsureCompiledJob.$anonfun$ensureIndexedModules$1$adapted(EnsureCompiledJob.scala:63)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.enso.interpreter.instrument.job.EnsureCompiledJob.ensureIndexedModules(EnsureCompiledJob.scala:63)
	at org.enso.interpreter.instrument.job.EnsureCompiledJob.run(EnsureCompiledJob.scala:45)
	at org.enso.interpreter.instrument.job.EnsureCompiledJob.run(EnsureCompiledJob.scala:33)
	at org.enso.interpreter.instrument.execution.JobExecutionEngine$$anon$1.call(JobExecutionEngine.scala:65)
	at org.enso.interpreter.instrument.execution.JobExecutionEngine$$anon$1.call(JobExecutionEngine.scala:60)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread.run(PolyglotThread.java:87)
```

After that each attach visualization request results in Service Error, and the following log in PM:
```
[error] [2020-11-23T15:02:21.732Z] [org.enso.languageserver.requesthandler.visualisation.AttachVisualisationHandler] Request Number(103) timed out
[info] [2020-11-23T15:02:26.732Z] [akka.actor.LocalActorRef] Message [org.enso.languageserver.requesthandler.RequestTimeout$] from Actor[akka://language-server-cc8235f4-3974-4b06-af5d-b9241b09a13b/user/$a/request-handler-AttachVisualisation-011f0cec-e1cb-4188-9e54-ec10728f9c27#-496182660] to Actor[akka://language-server-cc8235f4-3974-4b06-af5d-b9241b09a13b/user/$a/request-handler-AttachVisualisation-011f0cec-e1cb-4188-9e54-ec10728f9c27#-496182660] was not delivered. [3] dead letters encountered. If this is not an expected behavior then Actor[akka://language-server-cc8235f4-3974-4b06-af5d-b9241b09a13b/user/$a/request-handler-AttachVisualisation-011f0cec-e1cb-4188-9e54-ec10728f9c27#-496182660] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```

### Enso Version

Enso Project Manager
Version:    0.1.0
Built with: scala-2.13.3 for GraalVM 20.2.0
Built from: main* @ e62f6796fe39453a88a139a966a396f40ead6eba
Running on: OpenJDK 64-Bit Server VM, GraalVM Community, JDK 11.0.8+10-jvmci-20.2-b03
            Linux 5.4.77-1-MANJARO (amd64)

Tested on IDE build 351fb2bf

### PR DESCRIPTION
**Pull request by 4e6**
### Pull Request Description

close #1304 
close #1309 

Changelog:
- fix the issue when duplicate execution jobs were never canceled. I.e each file edit event triggered the program execution, resulting in other jobs (like visualization) being queued.
- fix the issue in the file edit handler, when the edits can be received in a different order.

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the [Scala](https://github.com/enso-org/enso/blob/main/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/main/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/main/docs/style-guide/rust.md) style guides.
- [x] All documentation and configuration conforms to the [markdown](https://github.com/enso-org/enso/blob/main/docs/style-guide/markdown.md) and [YAML](https://github.com/enso-org/enso/blob/main/docs/style-guide/yaml.md) style guides.
- [x] All code has been tested where possible.

### CODE REVIEW

File: engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/EditFileCmd.scala [hunk 1]
```diff
@@ -20,17 +22,21 @@ class EditFileCmd(request: Api.EditFileNotification) extends Command(None) {
...
-      _ <-
-        if (status == EnsureCompiledJob.CompilationStatus.Success)
-          Future.traverse(executeJobs)(ctx.jobProcessor.run)
-        else
-          Future.successful(())
-    } yield ()
+    ctx.locking.acquireFileLock(request.path)
+    try {
+      ctx.executionService.getLogger
+        .log(Level.FINE, s"EditFileCmd ${request.path}")
```
Comment (iamrecursion) [inline engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/EditFileCmd.scala:28]: Is this logging new? If so, we should probably use the new logging infra.

Comment (4e6) [reply engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/EditFileCmd.scala:28]: It's not new. Truffle provides it's own logging facilities (TruffleLogger), that should be used in runtime. Runtime logger is configured during the context creation in the language server.

**Review by kustosz — APPROVED** [review]
