### PR TITLE
Install Required GraalVM Components

### LINKED ISSUE #1645: Project Manager Should Prioritize Bundled Runtime
### General Summary

The project manager bundle uses local JVM runtime located at `~/.local/share/enso/runtime` even if the bundled one is available:

```
.
├── bin
│   └── project-manager
├── dist
│   └── 0.5.19
├── runtime
│   └── graalvm-ce-java11-21.0.0.2
└── THIRD-PARTY
```

### Steps to Reproduce

1. Download the project-manager bundle (tested with a 0.5.19 [staging release](https://github.com/enso-org/enso-staging/releases/tag/untagged-4f463de63d24169fa87a) 
2. Extract and start the project manager
3. Run the IDE with `--no-backend` flag
    ```
    ./enso-linux-2.0.0-alpha.2.AppImage --dev --no-backend
    ```
4. `ps` shows that the language server is using the local JVM runtime
    ```
    $ ps -ef | grep java
    dbushev   298050  297863 65 17:29 pts/8    00:02:00 /home/dbushev/.local/share/enso/runtime/graalvm-ce-java11-21.0.0.2/bin/java -Dpolyglot.engine.IterativePartialEscape=true -Dtruffle.class.path.append=/home/dbushev/Downloads/enso-project-manager-0.5.19-linux-amd64/enso/dist/0.5.19/component/runtime.jar -jar /home/dbushev/Downloads/enso-project-manager-0.5.19-linux-amd64/enso/dist/0.5.19/component/runner.jar --logger-connect ws://localhost:39415/ --server --root-id 45be41b5-9c64-42e9-bac3-a359fc6661b9 --path /home/dbushev/enso/projects/Test_R --interface 127.0.0.1 --rpc-port 59015 --data-port 61124 --log-level info
    ```

5. If you remove the local runtime, the project manager starts using the bundled one.

### Expected Result

The project manager uses the bundled JVM runtime even if the local one is available.

### Actual Result

The project manager always uses local JVM runtime if available.

### Enso Version

main @ 117ca51921c3475a39e7874d74a8185b9341af26

### PR DESCRIPTION
**Pull request by 4e6**
### Pull Request Description

close #1645

The project manager ensures that the required GraalVM components are installed. The logic is triggered in two cases: after the new GraalVM installation, and during the lookup of the existing runtime to make sure that the previously installed version has all required features.

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the [Scala](https://github.com/enso-org/enso/blob/main/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/main/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/main/docs/style-guide/rust.md) style guides.
- [x] All documentation and configuration conforms to the [markdown](https://github.com/enso-org/enso/blob/main/docs/style-guide/markdown.md) and [YAML](https://github.com/enso-org/enso/blob/main/docs/style-guide/yaml.md) style guides.
- [x] All code has been tested where possible.

### CODE REVIEW

File: lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/GraalVMComponent.scala [hunk 1]
```diff
@@ -0,0 +1,11 @@
+package org.enso.runtimeversionmanager.components
+
+/** A component of the GraalVM distribution. */
+case class GraalVMComponent(id: String)
+
+object GraalVMComponent {
+
+  val js: GraalVMComponent     = GraalVMComponent("js")
```
Comment (iamrecursion) [inline lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/GraalVMComponent.scala:8]: JS is installed by default.

**Review by iamrecursion — APPROVED** [review]

File: lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/GraalVMComponentUpdater.scala [hunk 2]
```diff
@@ -0,0 +1,101 @@
...
+  }
+
+  private object Paths {
+
+    /** Path to the java home directory in the runtime distribution. */
+    def javaHome: Path = os match {
+      case OS.Linux   => runtime.path
+      case OS.MacOS   => runtime.path / "Contents" / "Home"
+      case OS.Windows => runtime.path
+    }
```
Comment (radeusgd) [inline lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/GraalVMComponentUpdater.scala]: This is redundant to what is already in `GraalRuntime`.

File: lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/RuntimeVersionManager.scala [hunk 3]
```diff
@@ -704,7 +715,14 @@ class RuntimeVersionManager(
           )
         }
 
+        installRequiredRuntimeComponents(runtime, os).getOrElse {
+          throw InstallationError(
+            "fatal: Cannot install the required runtime components."
+          )
```
Comment (radeusgd) [inline lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/RuntimeVersionManager.scala:721]: This looks bad.

It throws an error but does nothing to revert the installation, so it has in fact succeeded.

I think we should either decide to warn and succeed or revert completely.

The easiest solution would be to move this *before* the `atomicMove`, so that the components are installed to the temporary runtime (because I understand that it is safe to move them, right?) and then only moved to the right place if the installation succeeds. If you move it there, throwing the error as is done right now will be enough because the temporary runtime *is* reverted on failure. The not-temporary runtime would have to be explicitly reverted, as seen above in the line `FileSystem.removeDirectory(runtimePath)`.

**Review by radeusgd — APPROVED** [review]
Looks really great.

Just one minor comment (the `javaHome` logic seems redundant) and one slightly more important one - the installation logic should handle failure more carefully.

File: lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/GraalVMComponentUpdater.scala (hunk 2 above)
Comment (4e6) [reply lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/GraalVMComponentUpdater.scala]: That explains why updater tests failed on macOS

File: lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/RuntimeVersionManager.scala (hunk 3 above)
Comment (4e6) [reply lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/RuntimeVersionManager.scala:721]: Thanks! I'll just do the update in the temporary directory
