### PR TITLE
Synchronize Runtime Updates Sending

### LINKED ISSUE #1594: Visualization Updates Randomly Failing
### General Summary
This is a tricky, non-deterministic one.

Visualization updates seem to randomly fail, leading to outdated visualization state.

See the video:

https://user-images.githubusercontent.com/1548407/111669570-39c88500-8817-11eb-97ea-dc81d6a03428.mp4

Timestamp 0:53 — I change `0.9` to `0.1
` but no updates are sent.

### Steps to Reproduce
Does not always happen. But usually it does.

Open the attached project.

[Unnamed.zip](https://github.com/enso-org/enso/files/6166127/Unnamed.zip)

Show visualization on the node, switch to table.

Observe values.
Then edit the second attached node by continuously switching between 0.1 and 0.9.
Eventually such change will not trigger a visualization update and the visualization will remain on old, outdated values.

When this happens, the project manager prints in log:
```
[warn] [2021-03-18T17:02:45.433Z] [org.enso.languageserver.protocol.json.JsonConnectionController] Received unknown message: VisualisationEvaluationFailed(07aec742-c457-4a3c-a208-02cfdf883b04,null)
```

### Expected Result
After each edit all visualizations receive updated bringing them up to date to the current program's state.

### Enso Version
0.2.7

### PR DESCRIPTION
**Pull request by 4e6**
### Pull Request Description

close #1594

PR adds `UpdatesSynchronizationState` that manages the runtime update messages and tracks which updates are sent to the user. The new logic covers situations when the runtime state has changed, but the program thread was interrupted before the runtime was able to prepare and send appropriate updates to the user.

Changelog
- add: `UpdatesSynchronizationState` that manages the state of runtime updates
- refactor: move runtime tests related to visualisations to a separate `RuntimeVisualisationsTest` suite

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the [Scala](https://github.com/enso-org/enso/blob/main/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/main/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/main/docs/style-guide/rust.md) style guides.
- [x] All documentation and configuration conforms to the [markdown](https://github.com/enso-org/enso/blob/main/docs/style-guide/markdown.md) and [YAML](https://github.com/enso-org/enso/blob/main/docs/style-guide/yaml.md) style guides.
- [x] All code has been tested where possible.

### CODE REVIEW

File: engine/runtime/src/main/java/org/enso/interpreter/instrument/UpdatesSynchronizationState.java [hunk 1]
```diff
@@ -0,0 +1,154 @@
+package org.enso.interpreter.instrument;
```
Comment (iamrecursion) [inline engine/runtime/src/main/java/org/enso/interpreter/instrument/UpdatesSynchronizationState.java:1]: Unless I'm missing something it seems like this implementation can race itself. You probably want to synchronize each modification on the thing being modified.

**Review by iamrecursion — CHANGES_REQUESTED** [review]

File: engine/runtime/src/main/java/org/enso/interpreter/instrument/UpdatesSynchronizationState.java (hunk 1 above)
Comment (4e6) [reply engine/runtime/src/main/java/org/enso/interpreter/instrument/UpdatesSynchronizationState.java:1]: Good catch! I added synchronization to all methods :+1:

**Review by iamrecursion — APPROVED** [review]
