### PR TITLE
Store Project Manager Metadata in Project Directory

### LINKED ISSUE #1110: Language server issue when project name is different in project.yaml from catalogue's name
### General Summary
If project name is different in project.yaml from catalogue's name, Enso studio cannot run the code

### Steps to Reproduce

1. change project catalog's name without modifying project.yaml file
2. run Enso Studio

### Expected Result

Project.yaml is updated by language server

### Actual Result

Application can't find project_name.Main, loads file but cannot execute it.

### PR DESCRIPTION
**Pull request by 4e6**
### Pull Request Description

close #1110 

PR changes the Project Manager to store its metadata inside the project directory, instead of maintaining the global index.
This will allow users to move and modify files inside the `~/enso` directory.

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the [Scala](https://github.com/enso-org/enso/blob/main/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/main/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/main/docs/style-guide/rust.md) style guides.
- [x] All documentation and configuration conforms to the [markdown](https://github.com/enso-org/enso/blob/main/docs/style-guide/markdown.md) and [YAML](https://github.com/enso-org/enso/blob/main/docs/style-guide/yaml.md) style guides.
- [x] All code has been tested where possible.

### CODE REVIEW

**Review by lolczak — CHANGES_REQUESTED** [review]
Some minor tweaks needed. Check how the `Traverse` class is implemented in Cats lib.

**Comment by 4e6** [comment]
Changelog
- add `ZioTraverse` instance
- add `NotDirectory` error
- update zio to `1.0.1`

**Comment by 4e6** [comment]
@radeusgd my logic was that each tool in the project uses its own directory, so I called it `.enso`, similar to `.idea` and what other IDEs do. `.cache` is quite abstract and can be potentially used by some other tool.
\cc @kustosz

**Review by lolczak — CHANGES_REQUESTED** [review]
Check once again how `Traverse` is defined. It is a type class that enables traversal over a structure with an effect. So, it is defined for types you can traverse (lists, trees, option), it is not defined for effects.

**Comment by kustosz** [comment]
The name `.enso` is terrible – doesn't tell anything in a project  belonging to a language called `enso`. I'd think `.studio` or `.ide`, or whatever that is called these days.

**Comment by 4e6** [comment]
@radeusgd @kustosz we can make it `.studio`, I like it more than `.ide`

**Comment by 4e6** [comment]
@lolczak I'm struggling to find the right encoding for the traversable class.

If we want to define it on a collection `G[_]` for all effects `F`
```
  def traverse[F[+_, +_]: ???, E, A, B](xs: G[A])(f: A => F[E, B]): F[E, C[B]]
```

Then we need some abstraction `???` that can bind together `F[_, _]` and `G[_]`. The problem here is that they have different number of type arguments, and we can't use classic type classes here.

If we change `G[_]` to `G[_, _]` adding a parameter to conform `F[_, _]`, then it is troublesome to define such instance for a collection.

I can imagine it is the reason why `zio` library doesn't have the hierarchy of typeclasses and defines all methods on the `ZIO` type itself.

**Comment by lolczak** [comment]
You have to define either `Applicative` or `Apply` type class for effects with `map2` method:
```
trait Apply[F[+_, +_]] {

  def pure[A](value: A): F[Nothing, A]

  def map2[E, A, B, Z](fa: F[E, A], fb: F[E, B])(f: (A, B) => Z): F[E, Z]

}
```
Next define traverse:

```
trait Traverse[F[_]] {

  def traverse[G[+_, +_]: Apply, E, A, B](fa: F[A])(f: A => G[E, B]): G[E, F[B]]

}
```
an instance for list should look like this:
```
object ListTraverseInstance extends Traverse[List] {

  def traverse[G[+_, +_]: Apply, E, A, B](fa: List[A])(f: A => G[E, B]): G[E, List[B]] = 
    fa.foldRight(Apply[G].pure(List.empty)) { case (item, acc) => Apply[G].map2(f(item), acc)(_ :: _)) }

}
```

Does it make sense? (I was brainstorming above.)

**Comment by lolczak** [comment]
Another solution is to use Cats type classes. To achieve that you have to provide instance of `Applicative` for `ZIO` and do type projections.

**Comment by 4e6** [comment]
@lolczak Thanks, worked like a charm!

**Review by lolczak — APPROVED** [review]
LGTM

File: lib/scala/project-manager/src/main/scala/org/enso/projectmanager/control/core/Applicative.scala [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+
+  def apply[F[+_, +_]](implicit applicative: Applicative[F]): Applicative[F] =
+    applicative
+
+  implicit def zioApplicative[R]: Applicative[ZIO[R, +*, +*]] =
+    zioApplicativeInstance.asInstanceOf[Applicative[ZIO[R, +*, +*]]]
+
+  final private[this] val zioApplicativeInstance
+    : Applicative[ZIO[Any, +*, +*]] =
+    new ZioApplicative[Any]
```
Comment (radeusgd) [inline lib/scala/project-manager/src/main/scala/org/enso/projectmanager/control/core/Applicative.scala:41]: I assume that this cast is safe because of type erasure, but wouldn't it be better (safer) to just create a `new` instance with the right type inside of the `implicit def`? (Otherwise maybe at least a comment would be helpful here stating that this is indeed safe and shortly explaining why.)

File: lib/scala/project-manager/src/main/scala/org/enso/projectmanager/control/core/ApplicativeFunctionOps.scala [hunk 2]
```diff
@@ -0,0 +1,10 @@
+package org.enso.projectmanager.control.core
+
+class ApplicativeFunctionOps[F[+_, +_]: Applicative, E, A, B](
+  ff: F[E, A => B]
+) {
+
+  /** @inheritdoc */
```
Comment (radeusgd) [inline lib/scala/project-manager/src/main/scala/org/enso/projectmanager/control/core/ApplicativeFunctionOps.scala]: How is `inheritdoc` valid here if this method is not an override?

File: lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectManagementApiSpec.scala [hunk 3]
```diff
@@ -313,6 +321,57 @@ class ProjectManagementApiSpec
...
+            }
+          }
+            """)
+      //then
+      languageServerClient.expectJson(json"""
+          {
+            "jsonrpc":"2.0",
+             "id":1,
+             "error":{"code":6001,"message":"Session not initialised"}}
+            """)
```
Comment (radeusgd) [inline lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectManagementApiSpec.scala:370]: It is unclear to me how an error indicates a successful test here.
I guess it's because if the project couldn't be opened the error would be different, but I think a short explanation would be really helpful for future maintainers.

**Review by radeusgd — APPROVED** [review]
Looks good to me, but I left some questions.

File: lib/scala/project-manager/src/main/scala/org/enso/projectmanager/control/core/Applicative.scala (hunk 1 above)
Comment (4e6) [reply lib/scala/project-manager/src/main/scala/org/enso/projectmanager/control/core/Applicative.scala:41]: AFAIK is a trick to initialize the class once, instead of creating a new one each time the implicit function is called.

Comment (radeusgd) [reply lib/scala/project-manager/src/main/scala/org/enso/projectmanager/control/core/Applicative.scala:41]: Makes sense, although I wonder how big of a performance impact that has.
I think it may be worth at least adding a short comment about its correctness, because it goes around the type-system a bit.

File: lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectManagementApiSpec.scala (hunk 3 above)
Comment (radeusgd) [reply lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectManagementApiSpec.scala:370]: Thanks!

File: lib/scala/project-manager/src/main/scala/org/enso/projectmanager/control/core/Applicative.scala (hunk 1 above)
Comment (4e6) [reply lib/scala/project-manager/src/main/scala/org/enso/projectmanager/control/core/Applicative.scala:41]: I think it's ok to leave it like that because it repeats itself in the codebase and forms a pattern. Also, it's not hard to see how `zioApplicative` function and `zioApplicativeConstant` are interacting. Too many comments is also not a good thing.
