### PR TITLE
Catch Polyglot Exceptions

### LINKED ISSUE #1168: Recover from Java Exceptions
main @ bd9689a2b43cceb2bab4f53be42a9796a6e7edfb

### General Summary

Currently, we can not catch Java exceptions.

```python
from Base import all
polyglot java import java.time.Instant

main = 
    result = Panic.recover (Instant.parse [""])
    IO.println result
```

```
Execution finished with an error: Text '' could not be parsed at index 0
        at <java> java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2046)
        at <java> java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1948)
        at <java> java.base/java.time.Instant.parse(Instant.java:395)
        at <enso> <polyglot_dispatch>(Internal)
        at <enso> argument<1>(src/Main.enso:5:29-46)
        at <enso> Panic.catch(Internal)
        at <enso> Main.main(src/Main.enso:5:14-47)
```

### Motivation

An ability to handle exceptions makes better interop with Java.

### PR DESCRIPTION
**Pull request by 4e6**
### Pull Request Description

close #1168 

`Panic.recover` catches host exceptions wrapping them in `Polyglot_Error` atom constructor.

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the [Scala](https://github.com/enso-org/enso/blob/main/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/main/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/main/docs/style-guide/rust.md) style guides.
- [x] All documentation and configuration conforms to the [markdown](https://github.com/enso-org/enso/blob/main/docs/style-guide/markdown.md) and [YAML](https://github.com/enso-org/enso/blob/main/docs/style-guide/yaml.md) style guides.
- [x] All code has been tested where possible.

### CODE REVIEW

File: engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/ErrorsTest.scala [hunk 1]
```diff
@@ -133,5 +133,27 @@ class ErrorsTest extends InterpreterTest {
...
+          |
+          |main =
+          |    args = Array.new 1
+          |    args.set_at 0 "oops"
+          |    caught = Panic.recover (Long.parseLong args)
+          |    IO.println caught
+          |    unwrap = caught.catch <| case _ of
+          |        Polyglot_Error err -> err
+          |        _ -> "fail"
+          |    IO.println unwrap
```
Comment (kustosz) [inline engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/ErrorsTest.scala]: Please verify that `unwrap` is a legit polyglot object – try calling some method on it and see if the result is still usable.

File: engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/ErrorsTest.scala [hunk 2]
```diff
@@ -133,5 +133,27 @@ class ErrorsTest extends InterpreterTest {
...
     }
+
+    "catch polyglot errors" in {
+      val code =
+        """from Builtins import all
+          |polyglot java import java.lang.Long
+          |
+          |main =
+          |    args = Array.new 1
+          |    args.set_at 0 "oops"
```
Comment (kustosz) [inline engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/ErrorsTest.scala]:
```suggestion
          |    args = Array.new_1 "oops"
```

**Review by kustosz — APPROVED** [review]
Awesome stuff! One improvement for tests needed and
