### PR TITLE
Abandon Terminating Language Server

### LINKED ISSUE #1430: Error When Trying to Restart the IDE with Integrated Language Server
### General Summary

The following error occurs when trying to restart the IDE with the integrated language server.

ide-language-server-shutdown-error

### Steps to Reproduce

1. Download IDE codebase
2. run ./run watch.
3. Open localhost:8080 and see the IDE running there
4. Change a file, like src/js/lib/content/src/index.js , save the file, see Chrome relading and watch the error appearing there!

### Expected Result

IDE is restarted without errors.

### Actual Result

An error occurs when restarting the IDE.

### Enso Version

main @ f726cfe11908e85b10693b096ee848251b5757ec

### PR DESCRIPTION
**Pull request by 4e6**
### Pull Request Description

close #1430 

Wait for the LS shutdown, spawn the new one, and only then reply to the client.

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the [Scala](https://github.com/enso-org/enso/blob/main/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/main/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/main/docs/style-guide/rust.md) style guides.
- [x] All documentation and configuration conforms to the [markdown](https://github.com/enso-org/enso/blob/main/docs/style-guide/markdown.md) and [YAML](https://github.com/enso-org/enso/blob/main/docs/style-guide/yaml.md) style guides.
- [x] All code has been tested where possible.

### CODE REVIEW

File: lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerController.scala [hunk 1]
```diff
@@ -221,6 +221,7 @@ class LanguageServerController(
     case ServerDied =>
       log.error(s"Language server died [$connectionInfo]")
       context.stop(self)
+
```
Comment (radeusgd) [inline lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerController.scala:224]: This empty line seems unnecessary.

**Review by radeusgd — APPROVED** [review]
Looks great now - simple and safe :)
